### ISSUE TITLE
Signature type error on frontend to core conversion

### ISSUE THREAD

**Issue by cwgoes** [metastatedev/juvix#585]
Right now, when trying to convert anything from frontend to core (from the example contracts), I get:

```bash
WrongSigType Nothing
```

It looks like this is coming from [this line](https://github.com/metastatedev/juvix/blob/develop/src/Juvix/Core/FromFrontend.hs#L426).

Any ideas? Maybe we should alter the error message to make it more descriptive?

This issue can be replicated on `develop` with:

```bash
make test-typecheck
```

(which just calls `contextToCore`)

**Comment by andy-morris** [comment]
The error `WrongSigType Nothing` means that the signature is not in scope. It should get a custom `Show` instance (or a pretty-printing instance, when we have those) at some point to be more clear.

Anyway the actual problem here is that `transformDef` expects `transformSig` to have been called first on the whole context, so `contextToCore` needs to do that.

I'm working on this in #587.
